### ISSUE TITLE
Eclipse Neon doesn't have org.eclipse.equinox.log anymore

### ISSUE THREAD

**Issue by hedayat** [ljader/redmine-mylyn-plugin#74] opened 2016-05-30 07:58 UTC
It is omitted from Neon repositories:
http://dev.eclipse.org/mhonarc/lists/rt-pmc/msg04526.html

If possible, please remove this dependency.

**Comment by failnix** [comment] 2016-07-13 12:54
Does anybody has an idea how to fix this? I really like this plugin and thats for me the only reason to stay on eclipse mars :(

**Comment by nhtones** [comment] 2016-07-13 12:58
Hi this is a duplicate of https://github.com/ljader/redmine-mylyn-plugin/issues/12

We got round it by adding the old eclipse update site (http://download.eclipse.org/eclipse/updates/4.2) and make sure the resolve all dependencies is ticked.

**Comment by ljader** [comment] 2016-11-14 22:39
Hi all,
Just to let you know, I think I'm onto right track to fix this issue.

**Comment by hedayat** [comment] 2016-11-15 13:24
Thanks :)

**Comment by stlimtat** [comment] 2016-11-24 15:25
I just did the changes to remove the need to org.eclipse.equinox.log, and submitted a pull request.  Pls check and verify if this works well.  I've tested and it works.

https://github.com/stlimtat/redmine-mylyn-plugin

**Comment by Abacab** [comment] 2017-01-06 17:33
Hi,
I am not a Java developer and I do not know how to compile a plugin for Eclipse. Could someone give me the plugin compiled so that I can install it in my Eclipse Neon? Thank you in advance.

**Comment by stlimtat** [comment] 2017-01-07 02:54
_/edited by maintainer - ljader - please use recently fixed 0.5.1 version of the plugin._

**Comment by Abacab** [comment] 2017-01-08 20:04
Thank you so much stlimtat,
I installed it with Neon 2 and it works perfectly.

**Comment by failnix** [comment] 2017-01-09 07:50
Hi

I upgraded from 0.4.0 to 0.4.1-Snapshot and still got the problem that the ticketnumbers for new created tickets doesn't show up anymore in the task list view. I've this behaviour since I've upgrade to the newest mylyn version 3.21.0. in neon.2

Does anybody else has this problem?

**Comment by el95149** [comment] 2017-01-09 07:58
Hello.
I'm facing the same issue (i.e. newly created ticket numbers not showing up) as well.
Running Eclipse Neon.2 with MyLyn 3.21.0 .

**Comment by raZieL777** [comment] 2017-01-10 16:15
Hello,

I am also facing this issue.

@ljader said that he was "on right track to fix this issue."
Can you give us an update? Would it be possible to assist w/ dev?

Thanks!

**Comment by chokribs** [comment] 2017-03-17 13:45
With Neon, it need to place "org.eclipse.equinox.log 1.2.0" jar (from http://maven.repository.paxle.net/org/eclipse/equinox/log/1.2.0.v20090520-1800/) under eclipse/plugins folde

**Comment by ljader** [comment] 2017-10-25 21:10
Hi all.
This has been fixed in new 0.5.1 version of the plugin - https://github.com/ljader/redmine-mylyn-plugin/releases

Thank you all for your help.

**Closed by ljader** 2017-10-25 21:10 UTC
