### ISSUE TITLE
Issue numbers are no longer shown with latest Eclipse

### ISSUE THREAD

**Issue by hedayat** [ljader/redmine-mylyn-plugin#76] opened 2017-01-11 05:20 UTC
Updating my Eclipse Neon to latest updates, it no longer shows issue numbers for newly created issues (it still shows the numbers for older issues). The number is certainly read from the server, because it is used for example when you want to create a new branch when an issue is active, it uses the issue number for naming the new branch.
Others have also seen this issue, as reported in issue #74

**Comment by ljader** [comment] 2017-01-22 21:51
I think this change in Mylyn caused this issue, but I need to investigate it a little bit more:
[https://bugs.eclipse.org/bugs/show_bug.cgi?id=497412](https://bugs.eclipse.org/bugs/show_bug.cgi?id=497412)

**Comment by MarKett** [comment] 2017-02-13 14:12
I had the same problem with automatic issue numbers in commit messages. The name of the issue key variable changed. I had to replace ${task.key} with ${task.id}

Maybe this can resolve this issue too?

**Comment by rombert** [comment] 2017-03-07 21:39
For the record, here are the fixes I needed to apply for the MantisBT connector after the Mylyn change

- https://github.com/Mylyn-Mantis/mylyn-mantis/commit/586eff5bca985f8ec55bbeb6a1822695b89027e7
- https://github.com/Mylyn-Mantis/mylyn-mantis/commit/1c506cc04e2ed0324167548e73fb950d23e9a4bf

**Comment by failnix** [comment] 2017-03-30 14:24
Is this project dead?

**Comment by ljader** [comment] 2017-03-30 16:07
@failnix I believe it's not, just sometimes lide gets in the way :)

I'm planning to fix this in April, fingers crossed.

**Comment by YSavanier** [comment] 2017-05-05 09:11
Hello, any news ? Can we help you ?

**Comment by scriptninja** [comment] 2017-07-03 18:06
Pahjbo's [fork](https://github.com/pahjbo/redmine-mylyn-plugin) seems to have this issue fixed. I forked from him and managed to get a travis-ci configuration set up that built the update site so I could confirm it works. I haven't found any issues with it.

**Comment by ljader** [comment] 2017-10-25 21:02
Hi all.
This has been fixed in new 0.5.1 version of the plugin - https://github.com/ljader/redmine-mylyn-plugin/releases

Thank you all for your help.

**Closed by ljader** 2017-10-25 21:02 UTC

**Comment by pahjbo** [comment] 2017-10-31 11:20
actually for me this "fix" did not work - as it then includes the "id" in the POST for an issue update which in turn causes a 

`
Completed 500 Internal Server Error in 234ms (ActiveRecord: 26.9ms)
NoMethodError (undefined method `id' for nil:NilClass):
  plugins/redmine_mylyn_connector/lib/mylyn_connector/hooks/controller_issues_edit_after_save.rb:16:in `block in controller_issues_edit_after_save'
  plugins/redmine_mylyn_connector/lib/mylyn_connector/hooks/controller_issues_edit_after_save.rb:15:in `controller_issues_edit_after_save'
`

This is with the redmine mylyn connector 2.8.2.stable in redmine 3.3.1.stable

**Comment by ljader** [comment] 2017-10-31 21:32
@pahjbo I've tried to reproduce the issue but without a luck.
Could you please share the detailed stacktrace of the issue from log?
(I assume you've spotted this in redmine/logs/production.log)

I'm looking for something like:
Started PUT "/issues/42.xml"
Processing by IssuesController#update as XML
Parameters: { issue full json}

**Comment by pahjbo** [comment] 2017-11-01 10:33
Actually it turns out that the problem is the interaction with another plugin - redmine_watcher_groups - so indeed the issue id not being displayed problem is solved
